@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package games.moegirl.sinocraft.sinocore.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;